//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class OptionsApiServerPage : global::System.Configuration.ApplicationSettingsBase
    {
        private static OptionsApiServerPage defaultInstance = ((OptionsApiServerPage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OptionsApiServerPage())));

        public static OptionsApiServerPage Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableApiServer
        {
            get
            {
                return ((bool)(this["EnableApiServer"]));
            }
            set
            {
                this["EnableApiServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiServerUrl
        {
            get
            {
                return ((string)(this["ApiServerUrl"]));
            }
            set
            {
                this["ApiServerUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiServerUsername
        {
            get
            {
                return ((string)(this["ApiServerUsername"]));
            }
            set
            {
                this["ApiServerUsername"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiServerPassword
        {
            get
            {
                return ((string)(this["ApiServerPassword"]));
            }
            set
            {
                this["ApiServerPassword"] = value;
            }
        }
    }
}
