//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorMapTheme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorMapTheme() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mRemoteNG.Resources.Themes.ColorMapTheme", typeof(ColorMapTheme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;Button&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Background {
            get {
                return ResourceManager.GetString("Button_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Border {
            get {
                return ResourceManager.GetString("Button_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Disabled_Background {
            get {
                return ResourceManager.GetString("Button_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Disabled_Border {
            get {
                return ResourceManager.GetString("Button_Disabled_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonDisabled&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Disabled_Foreground {
            get {
                return ResourceManager.GetString("Button_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;Button&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Foreground {
            get {
                return ResourceManager.GetString("Button_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonHover&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Hover_Background {
            get {
                return ResourceManager.GetString("Button_Hover_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderHover&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Hover_Border {
            get {
                return ResourceManager.GetString("Button_Hover_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonHover&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Hover_Foreground {
            get {
                return ResourceManager.GetString("Button_Hover_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonPressed&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Pressed_Background {
            get {
                return ResourceManager.GetString("Button_Pressed_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderPressed&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Pressed_Border {
            get {
                return ResourceManager.GetString("Button_Pressed_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonPressed&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Button_Pressed_Foreground {
            get {
                return ResourceManager.GetString("Button_Pressed_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Background {
            get {
                return ResourceManager.GetString("CheckBox_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Border {
            get {
                return ResourceManager.GetString("CheckBox_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxBorderDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Border_Disabled {
            get {
                return ResourceManager.GetString("CheckBox_Border_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxBorderHover&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Border_Hover {
            get {
                return ResourceManager.GetString("CheckBox_Border_Hover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxBorderPressed&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Border_Pressed {
            get {
                return ResourceManager.GetString("CheckBox_Border_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxGlyph&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Glyph {
            get {
                return ResourceManager.GetString("CheckBox_Glyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxGlyphDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Glyph_Disabled {
            get {
                return ResourceManager.GetString("CheckBox_Glyph_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxText&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Text {
            get {
                return ResourceManager.GetString("CheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;CheckBoxTextDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_Text_Disabled {
            get {
                return ResourceManager.GetString("CheckBox_Text_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBox&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Background {
            get {
                return ResourceManager.GetString("ComboBox_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Border {
            get {
                return ResourceManager.GetString("ComboBox_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButton&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_Background {
            get {
                return ResourceManager.GetString("ComboBox_Button_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_Border {
            get {
                return ResourceManager.GetString("ComboBox_Button_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButton&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_Foreground {
            get {
                return ResourceManager.GetString("ComboBox_Button_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonMouseOver&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_MouseOver_Background {
            get {
                return ResourceManager.GetString("ComboBox_Button_MouseOver_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonMouseOverBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_MouseOver_Border {
            get {
                return ResourceManager.GetString("ComboBox_Button_MouseOver_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonMouseOver&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_MouseOver_Foreground {
            get {
                return ResourceManager.GetString("ComboBox_Button_MouseOver_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonPressed&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_Pressed_Background {
            get {
                return ResourceManager.GetString("ComboBox_Button_Pressed_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxButtonPressed&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Button_Pressed_Foreground {
            get {
                return ResourceManager.GetString("ComboBox_Button_Pressed_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Disabled_Background {
            get {
                return ResourceManager.GetString("ComboBox_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxDisabled&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Disabled_Foreground {
            get {
                return ResourceManager.GetString("ComboBox_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBox&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_Foreground {
            get {
                return ResourceManager.GetString("ComboBox_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxMouseOverBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_MouseOver_Border {
            get {
                return ResourceManager.GetString("ComboBox_MouseOver_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxPopUpBorder&apos;]/ComboBoxPopUp/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_PopUp {
            get {
                return ResourceManager.GetString("ComboBox_PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ComboBoxPopUpBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_PopUp_Border {
            get {
                return ResourceManager.GetString("ComboBox_PopUp_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Environment&apos;]/Color[@Name=&apos;CommandShelfHighlightGradientBegin&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CommandBarMenuDefault_Background {
            get {
                return ResourceManager.GetString("CommandBarMenuDefault_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Environment&apos;]/Color[@Name=&apos;CommandBarTextActive&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string CommandBarMenuDefault_Foreground {
            get {
                return ResourceManager.GetString("CommandBarMenuDefault_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;Dialog&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Background {
            get {
                return ResourceManager.GetString("Dialog_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;Dialog&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Foreground {
            get {
                return ResourceManager.GetString("Dialog_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler error&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ErrorText_Background {
            get {
                return ResourceManager.GetString("ErrorText_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler error&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string ErrorText_Foreground {
            get {
                return ResourceManager.GetString("ErrorText_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabActiveBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Backgorund {
            get {
                return ResourceManager.GetString("GroupBox_Backgorund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabInactiveBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Disabled_Background {
            get {
                return ResourceManager.GetString("GroupBox_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabInactiveText&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Disabled_Foreground {
            get {
                return ResourceManager.GetString("GroupBox_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabInactiveBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Disabled_Line {
            get {
                return ResourceManager.GetString("GroupBox_Disabled_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabActiveText&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Foreground {
            get {
                return ResourceManager.GetString("GroupBox_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;InnerTabActiveBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string GroupBox_Line {
            get {
                return ResourceManager.GetString("GroupBox_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Background {
            get {
                return ResourceManager.GetString("List_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListHeader&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Header_Background {
            get {
                return ResourceManager.GetString("List_Header_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListHeader&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Header_Foreground {
            get {
                return ResourceManager.GetString("List_Header_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItem&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Background {
            get {
                return ResourceManager.GetString("List_Item_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Border {
            get {
                return ResourceManager.GetString("List_Item_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Disabled_Background {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabledBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Disabled_Border {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabled&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Disabled_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItem&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelected&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Selected_Background {
            get {
                return ResourceManager.GetString("List_Item_Selected_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelectedBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Selected_Border {
            get {
                return ResourceManager.GetString("List_Item_Selected_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelected&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string List_Item_Selected_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Selected_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;ProgressBar&apos;]/Color[@Name=&apos;Background&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ProgressBar_Background {
            get {
                return ResourceManager.GetString("ProgressBar_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;ProgressBar&apos;]/Color[@Name=&apos;IndicatorFill&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ProgressBar_Fill {
            get {
                return ResourceManager.GetString("ProgressBar_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;ProgressBar&apos;]/Color[@Name=&apos;IndicatorFillCritical&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ProgressBar_Fill_Critical {
            get {
                return ResourceManager.GetString("ProgressBar_Fill_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;ProgressBar&apos;]/Color[@Name=&apos;IndicatorFillWarning&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string ProgressBar_Fill_Warning {
            get {
                return ResourceManager.GetString("ProgressBar_Fill_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;TabBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Tab_Background {
            get {
                return ResourceManager.GetString("Tab_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;TabItem&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Tab_Item_Background {
            get {
                return ResourceManager.GetString("Tab_Item_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;TabItemDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Tab_Item_Disabled_Background {
            get {
                return ResourceManager.GetString("Tab_Item_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;TabItemDisabled&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Tab_Item_Disabled_Foreground {
            get {
                return ResourceManager.GetString("Tab_Item_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;TabItem&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Tab_Item_Foreground {
            get {
                return ResourceManager.GetString("Tab_Item_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackground&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Background {
            get {
                return ResourceManager.GetString("TextBox_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorder&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Border {
            get {
                return ResourceManager.GetString("TextBox_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorderDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Border_Disabled {
            get {
                return ResourceManager.GetString("TextBox_Border_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorderFocused&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Border_Focused {
            get {
                return ResourceManager.GetString("TextBox_Border_Focused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackgroundDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Disabled_Background {
            get {
                return ResourceManager.GetString("TextBox_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxTextDisabled&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Disabled_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackgroundFocused&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Focused_Background {
            get {
                return ResourceManager.GetString("TextBox_Focused_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxTextFocused&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Focused_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Focused_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxText&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TextBox_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;Background&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string TreeView_Background {
            get {
                return ResourceManager.GetString("TreeView_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;Background&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string TreeView_Foreground {
            get {
                return ResourceManager.GetString("TreeView_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemActive&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Treeview_SelectedItem_Active_Background {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Active_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemActive&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Treeview_SelectedItem_Active_Foreground {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Active_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemInactive&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string Treeview_SelectedItem_Inactive_Background {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Inactive_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemInactive&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string Treeview_SelectedItem_Inactive_Foreground {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Inactive_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler warning&apos;]/Background/@Source 的當地語系化字串。
        /// </summary>
        internal static string WarningText_Background {
            get {
                return ResourceManager.GetString("WarningText_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler warning&apos;]/Foreground/@Source 的當地語系化字串。
        /// </summary>
        internal static string WarningText_Foreground {
            get {
                return ResourceManager.GetString("WarningText_Foreground", resourceCulture);
            }
        }
    }
}
